### ISSUE TITLE
Email Config?

### ISSUE THREAD

**Issue by ddoherty03** [caisah/emacs.dz#14]
Nice list.  Would be nice to have a column that indicates whether an Emacs-based email config is part of the config.  I am bouncing between Wanderlust and mu4e and always looking for config tips.  Regards.

**Comment by caisah** [comment]
It sounds nice, but I don't think a separate column is the answer. Email config could also be mentioned in the _Highlights_ section.

**Comment by ddoherty03** [comment]
Sure, that sounds good.  But if done, it would be nice to say something system-specific like "mu4e", "wanderlust", "notmuch", "gnus", etc. so we could find good configurations for specific mailers.  Thanks.

**Comment by caisah** [comment]
Sure, I'll try to list this. Also feel free to open a pull request :)
