### ISSUE TITLE
Current link to Harry R. Schwartz's emacs config shows a 404

### ISSUE THREAD

**Issue by lmintmate** [caisah/emacs.dz#24]
The link that currently points towards his config ([https://github.com/hrs/dotfiles/tree/master/emacs.d](https://github.com/hrs/dotfiles/tree/master/emacs.d)) now shows a 404, because he changed his folder structure in the meanwhile. The link is now at [https://github.com/hrs/dotfiles/tree/master/emacs/.emacs.d](https://github.com/hrs/dotfiles/tree/master/emacs/.emacs.d).
Thanks in advance.

**Comment by caisah** [comment]
Thanks! Fixed it.
