### ISSUE TITLE
Question regarding adding new configurations

### ISSUE THREAD

**Issue by phikal** [caisah/emacs.dz#34]
Hi,

at the bottom of the `README.org` file you mention the following:

> Feel free to open a pull request. Please don’t add your personal config file. I won’t accept it unless it is vetted by other community members.

and I've seen you say something along these lines many times in the pull requests. Yet it seems a bit arbitrary to me ([and to others](https://lobste.rs/s/9ak7g6/list_people_with_nice_emacs_config_files)). Certain personal configurations _do get accepted_, like #28, while others just get rejected without any understandable explanation (#1, #2, #5, #7, ...). Just referring to the quote above, just let's people hope that they _might_ get accepted. 

Wouldn't it be better to set up some criteria, or minimum requirements to get added to the list? Or maybe one must highlight something original and/or noteworthy to get accepted, be it their configuration or not. I believe that this would not only increase the quality of the list, but also make it easier to maintain, since people would _know_ when it makes sense to suggest their configuration. Maybe one could even go beyond the table-format and create a properly structured org file with code snippets, images and what-not.

I hope there can be a conversation about this :)

**Comment by caisah** [comment]
Hi,

Most of the people on this list are either heavy contributors to MELPA or people who get involved in the community beyond having an .emacs.d dir. 

Of course anybody can get listed  but it has to be for some good reasons (either having an interesting config  or being active in the community). If I let anybody submit their config I may well create a script that lists all the configs out there.

I'm open to suggestions but currently I'm not looking to evolve this list into something else. There are a lot of elisp snippets all over the internet and on the wiki, so I don't want to create another place like that.
What people came with lately was no something to improve this list but only get a self listing.

**Comment by phikal** [comment]
> Most of the people on this list are either heavy contributors to MELPA or people who get involved in the community beyond having an .emacs.d dir.

Aha, that makes sense. I guess it wouldn't be bad to mention that. Might have the indirect effect of making people more eager to contribute back to the community?

> If I let anybody submit their config I may well create a script that lists all the configs out there.

What about setting up a shorter list of "See Also" (ala Wikipedia) configurations, that meat some minimal criteria. Sometimes I'd just like to have some central place to be able to find Emacs configurations, and on some level I was hoping to find that here.

**Comment by caisah** [comment]
> I guess it wouldn't be bad to mention that.

Good idea, I'll add this detail to the list.

> What about setting up a shorter list of "See Also" (ala Wikipedia) configurations, that meat some minimal criteria

That sounds good. I'll think about some criteria and list it. Feel free to suggest some :smile:

**Comment by Atman50** [comment]
I do have a literate config that I'm fairly proud of. Supports Emacs 27.0.50 -- not sure it goes back to earlier versions...
Anyway, I'd like to share and/or get feedback from this group: [Adam Taylor's Emacs config](https://github.com/Atman50/emacs-config)
Any feedback is greatly appreciated.

**Comment by SerialDev** [comment]
Feel free to have a look at https://github.com/SerialDev/tiqsi-emacs , its mostly used within a Docker and x11 server to make emacs on windows a much smoother experience.

**Comment by caisah** [comment]
@SerialDev Could you please open a pull request?

**Comment by michaelterryio** [comment]
I like this one:

https://github.com/patrickt/emacs

...from a GitHub guy that works on their Haskell lib to parse, analyze and compare source code for a long list of languages

it's got a blog post too:

https://blog.sumtypeofway.com/posts/emacs-config.html
