### ISSUE TITLE
Perhaps organize the list by features or config type. 

### ISSUE THREAD

**Issue by jordonbiondo** [caisah/emacs.dz#8]
Thanks for putting this together it's going to be a great resource! I think it would be more useful if each entry in the list contained a blurb about why it's on the list or what kind of config it is.

A simple starting point would be organizing the list by type, org-based, use-package, el-get, totally custom, starter-kit-esque etc.

Thoughts?

**Comment by caisah** [comment]
This sounds like a great idea. I didn't think of that, but it makes a lot of sense.

**Comment by caisah** [comment]
I guess a good starting point would be at least something similar to https://github.com/emacs-tw/awesome-emacs#noteworthy-configurations

**Comment by kaushalmodi** [comment]
I don't know what would be the best way to categorize these, but may be also add if the setup is evil-based or not.

**Comment by kaushalmodi** [comment]
May be have that list converted to an org table with columns for checks for emacs-style bindings, org-based, use-package organized, el-get, etc?

**Comment by caisah** [comment]
Yep, an org table is what popped into my mind in the first place but we should try and determine what are the most valuable things to add to those columns.

**Comment by kaushalmodi** [comment]
> determine what are the most valuable things

That would result in very subjective answers as it would depend very much on personal taste. As for me, the columns could be:

- Bindings style: emacs, vim, custom modal, etc.
- Org Literate config: yes, no
- Package fetcher/organizer: use-package, quelpa, el-get, hybrid of those?
- Mininum emacs version supported: 25.1, 24.5, ..
- Ready to clone and use: yes, no
